### ISSUE TITLE
1155 Clean Project import.

### ISSUE THREAD

**Issue by epicality85** [vis2k/uMMORPG#10]
**Versions (please complete the following information)**
 - Unity Version: [e.g. 2017.1.0f1]  2018.2.20f1
 - uMMORPG Version: [e.g. V1.0] 1.155
 - Are you using a fresh uMMORPG version without any modifications? [e.g. yes/no] yes
    If not, then please try to reproduce it in a fresh Version and come back here.

**Describe the bug**
Clean import produces 2 errors:
1. Assets/uMMORPG/Scripts/Database.cs(80,12): error CS0012: The type `System.Data.Common.DbConnection' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
2. Assets/uMMORPG/Scripts/Database.cs(204,59): error CS0012: The type `System.Data.Common.DbParameter' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor, add uMMORPG from asset store
5. See errors in console

**Expected behavior**
Assets should not import with errors into supported Unity versions

**Screenshots/Video**
N/A

**System (please complete the following information):**
 - Operating System [e.g. Windows 7] Windows 10

**Additional context**
N/A

**Comment by miwarnec** [comment]
seems to work with fine with latest version. just tried it from scratch with 2018.2.20.
