### ISSUE TITLE
Character Selection Bug

### ISSUE THREAD

**Issue by reyser-eth** [vis2k/uMMORPG#12]
**Versions **
 - Unity Version: 2018.3.61f
 - uMMORPG Version: 1.165
 - Are you using a fresh uMMORPG version without any modifications? Yes

**Describe the bug**
After character selection the character still standing on the hills.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor 
2. Hit Play (Server & Play)
3. Create Character & Hit Start
4. Look at the hills
5. The character still standing on the hills

**Expected behavior**
I thought the character should not be there.

**Screenshots/Video**
None

**System (please complete the following information):**
 - Operating System Windows 7

**Comment by miwarnec** [comment]
Seems fine when I try it:
![image](https://user-images.githubusercontent.com/16416509/55625787-0c10df80-57aa-11e9-909e-fb3c219cbd3d.png)
that bug was fixed a couple of weeks ago.
please try to download V1.166 from scratch and see if it still happens or not. please reopen if it does.
