### ISSUE TITLE
Skill bar Performance

### ISSUE THREAD

**Issue by Hawkadium** [vis2k/uMMORPG#13]
Versions:
Unity Version: [2018.3.14f1]
uMMORPG Version: [1.169]

Are you using a fresh uMMORPG version without any modifications?
Yes

Describe the bug:
Skill bar becomes a severe performance hog, with the more hot keyed skills you have added.

To Reproduce Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor
2. Press Run in Editor
3. Select Server and Play
4. Kill Monsters until sufficient Skill Points have been reached
5. Learn some skills
6. Open Profiler on second monitor
7. Open skill window and drag-n-drop skills onto Skill Bar
8. Watch an increased drain on CPU as more skills are added to Skill Bar

Expected behavior:
Expect skill bar to not use over half the hardware budget.

Screenshots/Video If applicable, add screenshots/videos to help explain your problem:
N/A

System:
Operating System [Windows 10 17763]

**Comment by miwarnec** [comment]
should be fixed now. the new tooltip.isvisible check solves it.
