### ISSUE TITLE
Spawn Prefabs now private on NetworkManager.cs

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#15]
All default uMMORPG3d / Mirror

spawnPrefabs variable in NetworkManager.cs (in Mirror) on line 48 is now PRIVATE

This will prevent users without coding knowledge to add anything to their spawnable prefabs list.

;-)

![spawnPrefabs](https://user-images.githubusercontent.com/40817126/59430009-626d5080-8de1-11e9-8431-b713a968940c.png)

**Comment by wovencode** [comment]
Actually its "Hidden in Inspector" and not private

**Comment by miwarnec** [comment]
@wovencode registered spawnable prefabs are still supposed to be in the Inspector:
![image](https://user-images.githubusercontent.com/16416509/60026643-3af96c00-969c-11e9-83a3-cbb9897ce3ab.png)

what exactly do you mean, that it should or should not be private?

**Comment by wovencode** [comment]
My error,
If you update from an older version they dont show up anymore,
happened to a few other people as well. Guess it depends on the
#Define - or whatever.

Fresh Install: They are visible

Update from old Version: Not visible without additional tweaks to
your Defines

**Comment by miwarnec** [comment]
strange. might work if people delete their library folder, but probably not worth worrying about since it affects older versions
