### ISSUE TITLE
OnStopServer / OnServerDisconnect not called in Editor mode

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#17]
OnStopServer / OnServerDisconnect are not called when in Editor mode, seems to be a Mirror issue. Might require a custom solution like the one found in OnApplicationQuit

Have not checked the other events, but might be same

Thats a bit unfortunate for us AddOn developers because the hooks therefore don't work either in editor mode.

Causes unnecessary questions from my clients...

**Comment by miwarnec** [comment]
taking a look now

**Comment by miwarnec** [comment]
nice find again @wovencode . will be fixed in next mirror version, and most likely in next ummorpg version
