### ISSUE TITLE
Entity position on the client is different to server causing scriptable skills distance condition to fail on the server only

### ISSUE THREAD

**Issue by trippah** [vis2k/uMMORPG#20]
**Versions (please complete the following information)**
- Unity 2018.3.11f, fresh ummo without modification
- ummo headless server on a remote server, client on windows

**Describe the bug**
If a skill.CheckDistance() is executed in a [server] block like UpdateServer_IDLE() on player.cs, CheckDistance() is executed on both the client and server.

Trying to cast a skill (slash) would sometimes fail as the skill CheckDistance method is returning different values on client and server, and on occasion the server value is greater than the skill.castRange that it does not cast the skill. From what I understand this happens because at times, the monster position is not synced on client and server.

**To Reproduce**
- Deploy headless server on a remote linux server and a client on windows.
- Add `Debug.Log("distance: " + Utils.ClosestDistance(caster.collider, caster.target.collider));` to CheckDistance() of TargetDamageSkill.cs this will echo the distance on both the client and server and at times the values will be different.

**Expected behavior**
 `Utils.ClosestDistance(caster.collider, caster.target.collider)` in skill.CheckDistance() should be the same value for both the client and server so that CheckDistance() will pass conditions on both the server and client

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/15664448/60590094-70a9fd80-9dde-11e9-8efa-9a487aac0e26.png)
(left is client, right is server value of `Utils.ClosestDistance(caster.collider, caster.target.collider)`)

**System (please complete the following information):**
 - Debian/Windows

**Comment by vis2k** [comment]
this happens because we use the collider distances.
the colliders are on the hips, and affected by animations.
sometimes, animations are happening at different times on server and client, hence different positions.

I have a few ideas around this problem. will keep you updated.

**Comment by vis2k** [comment]
fixed in V1.184: https://gyazo.com/f308e50115185db5cf576a55b2a76dff
