### ISSUE TITLE
Guild demote can end in 2 Vices

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#24]
Blank uMMORPG3d (or 2d, does not matter in that case) of most recent version

If a Vice demotes a Master, then the Guild ends up with 0 Master and 2 Vices.

**Comment by miwarnec** [comment]
can't reproduce.
I run host in editor, create guild, invite a client build.
promote client to vice.
client can't demote master.

perhaps you modified some of the guild code accidentally.
if it still happens in fresh project then let me know how to reproduce.
