### ISSUE TITLE
Short range teleportation not possible

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#26]
default uMMORPG3d/2d of most recent version
--

Using default Npc teleportation with a dedicated server running

--

Teleporting over very short distances is not possible (seems like the rubberbanding intercepts it). This way you cannot teleport players behind a door/wall for example, when it is very close.

**Comment by miwarnec** [comment]
can confirm. looking into it now.

**Comment by miwarnec** [comment]
fixed in V1.183 by introducing Entity.Warp function that is called instead of agent.Warp in state machines.
