### ISSUE TITLE
Monsters cannot activate mulitple skills

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#27]
version does not matter

--

when a monster has multiple skills and the first (or one of the first ones) has a Cooldown of 0, it always tries to activate only that skill(s). All other skills never have a chance to activate.

Randomizing activation order fixes this.

**Comment by miwarnec** [comment]
the skeleton boss has two skills, first one being normal attak with cooldown of 0.
it still works and casts the second skill too.
if your bug still happens in the latest version then please reopen and include details on how to reproduce.
