### ISSUE TITLE
conn.Disconnect() with Apathy

### ISSUE THREAD

**Issue by Ghetaldus** [vis2k/uMMORPG#29]
**Versions**
 - Unity Version: 2018.4.12f1
 - uMMORPG Version: 1.182
 - Are you using a fresh uMMORPG version without any modifications? Yes

**Describe the bug**
When using Apathy and conn.Disconnect() gets called to disconnect a client warnings that you can see in attached screenshot spams on client.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor
2. Build for Windows
3. Run Editor as Client
4. Run Build as Server Only
5. Create account and login
6. Stop playing editor and then start again
7. Type in wrong password when logging in again to get OnClientError to be run so conn.Disconnect() gets called
8. See warnings spammed in console on client

**Expected behavior**
To not get warnings spammed on client.

**System:**
 - Windows 10

**Additional context**
This works fine with Telepathy.

<img width="451" alt="apathy" src="https://user-images.githubusercontent.com/30866474/70823251-b7654000-1ddf-11ea-9fc4-e5907cb3b556.png">

**Comment by miwarnec** [comment]
fix will be in V1.183 thx
