### ISSUE TITLE
Namespaces are not used - its causing conflicts with another asset store assets

### ISSUE THREAD

**Issue by astromediaonly** [vis2k/uMMORPG#3]
**Versions (please complete the following information)**
 - Unity Version: 2017.4.11f1
 - uMMORPG Version: V1.140
 - Are you using a fresh uMMORPG version without any modifications? yes

**Describe the bug**
In my case class UIUtills is also used in Amplify Shader Editor (they are using namespaces tho). After import shader editor does not works and there are compilation errors caused by conflict with yours UIUtills class.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor 
2. Import Amplify Shader Editor assset 
3. See error

**Expected behavior**
Importing another assets from store where they are properly using namespaces should not make any conflicts.

**System (please complete the following information):**
 - Windows 10

**Comment by red7silence** [comment]
I really hope this is getting looked at. I brought this up 2 years ago, but was told it would take too much work. I want to be able to use other assets along with uMMORPG, but if this isn't fixed, I can't.

**Comment by miwarnec** [comment]
won't happen, sorry.
doing this now would break everyone's projects.
