### ISSUE TITLE
Characters not saved when they disconnect

### ISSUE THREAD

**Issue by Ghetaldus** [vis2k/uMMORPG#30]
**Versions (please complete the following information)**
 - Unity Version: 2018.4.12f1
 - uMMORPG Version: 1.182
 - Are you using a fresh uMMORPG version without any modifications? Yes

**Describe the bug**
When you close client OnServerDisconnect runs which calls DoServerDisconnect coroutine and that is supposed to save charecter to database. It does not do that anymore.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor '...'
2. Build for Windows '....'
3. Run Editor as server
4. Run Build as client
5. Start server only
6. Start client, create account and login
7. Create character and enter the game
8. Close/Quit client
9. Look in servers console that character has not been saved ("saved: characterName" message does not appear)

**Expected behavior**
When client disconnects character should be saved to database.

**System (please complete the following information):**
 - Windows 10

**Additional context**
This was working fine before latest few updates. I have just tested this with 1.179 version and that one works fine. I guess something have changed in Mirror.

**Comment by miwarnec** [comment]
looking into it now

**Comment by miwarnec** [comment]
can confirm, we broke Mirror :/

**Comment by miwarnec** [comment]
I fixed it: https://github.com/vis2k/Mirror/issues/1359
fix will be in next uMMORPG release.

**Comment by miwarnec** [comment]
nice find @Ghetaldus !
