### ISSUE TITLE
Skillbar not saved

### ISSUE THREAD

**Issue by Ghetaldus** [vis2k/uMMORPG#31]
**Versions (please complete the following information)**
 - Unity Version: 2018.4.12f1
 - uMMORPG Version: 1.183
 - Are you using a fresh uMMORPG version without any modifications? Yes

**Describe the bug**
When you close/logout client skillbar is not saved.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor '...'
2. Build for Windows '....'
3. Run Editor as server
4. Run Build as client
5. Start server only
6. Start client, create account and login
7. Create character and enter the game
8. Move default attack to another slot in skillbar
8. Close/Quit client
9. Start client again and log in with same character
10. Observe that default attack is back at first slot in skillbar

**Expected behavior**
Skillbar is to be saved when character logs out.

**System (please complete the following information):**
 - Windows 10

**Additional context**
It seems that with this Mirror version isClient is always false in OnDestroy() in Player.cs. That makes code bellow  if (!isServer && !isClient) return; line in OnDestroy() never run on client, therefore SaveSkillbar() never gets executed.

**Comment by miwarnec** [comment]
thanks, looking into it now

**Comment by miwarnec** [comment]
it's a mirror bug: https://github.com/vis2k/Mirror/issues/1475
working on a fix

**Comment by atem1x** [comment]
in 2d 1.53 same problem

**Comment by miwarnec** [comment]
fix is in V1.185 and will be ported to all other assets too. thanks for reporting.
