### ISSUE TITLE
from discord: pet bug

### ISSUE THREAD

**Issue by miwarnec** [vis2k/uMMORPG#33]
despawning pets despawns all npcs/monsters for a second, until they respawn.
most likely because pet is owned by player now, so removing pet removes player connection from them until rebuildobservers is called again.

this is not critical as things still work 1s later. but still want to look into it.

possible solutions:
- look into mirror code. probably something we should check
- spawn pet without player auth like before

**Comment by burnydev** [comment]
Video showing bug.

https://youtu.be/djKP3hhQmCM

**Comment by miwarnec** [comment]
https://github.com/vis2k/Mirror/issues/1598 working on it

**Comment by miwarnec** [comment]
fixed in V2.10
