### ISSUE TITLE
Skill experience points

### ISSUE THREAD

**Issue by Ghetaldus** [vis2k/uMMORPG#35]
**Versions (please complete the following information)**
 - Unity Version: 2019.3.4f1
 - uMMORPG Version: 1.187
 - Are you using a fresh uMMORPG version without any modifications? Yes

**Describe the bug**
When level difference between you and your victim is larger then x levels you will be receiving negative skill experience points.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor '...'
2. Run Editor as "Server & Play"
3. Create character and level him up to at least player level 14.
4. Kill a skeleton that is level 1.
5. Open Character Info and look at skill exp value. It is -1.

**Expected behavior**
There should not be skill experience points lose for killing lower level monsters then yourself.

**System (please complete the following information):**
 - Windows 10

**Additional context**
 - return value of BalanceExpReward() should never return anything below 0.

**Comment by Ghetaldus** [comment]
Simply changing clamping of levelDiff to be between -10 and 10 instead of -20 and 20 will make sure that multiplier can never be negative.

![image](https://user-images.githubusercontent.com/30866474/76330534-3a6a3980-62ee-11ea-9ddc-df5dde9daa85.png)

**Comment by miwarnec** [comment]
thanks, will take a look

**Comment by miwarnec** [comment]
@Ghetaldus nice find, fix is in classic V1.188 and CE V2.8 together with a test to make sure it never happens again:
![image](https://user-images.githubusercontent.com/16416509/76612857-64ee0980-651d-11ea-8106-f825f0fb346b.png)
