### ISSUE TITLE
Player and Enemy ignores the attack range for Melee Combat (a bug vis2k will never fix...)

### ISSUE THREAD

**Issue by jon-malave** [vis2k/uMMORPG#37]
> **Versions (please complete the following information)**
> 
> * Unity Version: [e.g. 2018.3.6f1]
> * uMMORPG Version: [e.g. V1.189]
> * Are you using a fresh uMMORPG version without any modifications? **YES**
>   If not, then please try to reproduce it in a fresh Version and come back here.
> 
> **Describe the bug**
> Player and Enemy ignores the attack range set for melee combat when testing using a Linux Headless Server with Websocket Transport.
> 
> **To Reproduce**
> Steps to reproduce the behavior, please explain every single click that is needed:
> 
> 1. Open Unity Editor
> 2. Build for Linux Server using Websocket Transport
> 3. Upload Linux Build to Server
> 4. Click Play in Editor and Connect to Server
> 5. After Player Spawns in-game Double Click a Skeleton To Attack
> 6. Notice Player and Skeleton run into each other and begin attacking at an Attack Range of 0 (meaning they are 100% colliding with each other's body), Instead they should be 1-2 feet away or whatever the default attack range is that is set for Melee Combat.
> 7. Stop Playing, Click Play in Editor again and test using Server & Play Option. Perform the same steps again and you will see the Player and Enemy Stop at the attack range set for Melee Combat. (they will not collide with each other's body unless the Player moves foward into the Skeleton using the WASD movement keys)
> 
> **Expected behavior**
> Player and Enemy Stop at the correct attack range set for Melee Combat.

**Comment by AbraKabastard** [comment]
Hello, same issue using default settings with Telepathy and apathy. Followed steps, same result!

> NetworkNavMeshAgent.OnDeserialize: new position not on NavMesh, name=Warrior(Clone) new position=(-5.1, 0.8, -23.0). This could happen if the agent was warped to a dungeon instance that isn't on the local player.

Edit: I removed AggroArea.cs from the Skeleton monsters and the positioning seemed to be fine. My character stopped before the Skeleton from the right distance. It looks like the skeleton is running at the player as the same time the player is running towards it and they dont brake

**Comment by miwarnec** [comment]
Hey guys. So this only happens in a build, not if you run host mode in Editor?

**Comment by AbraKabastard** [comment]
Correct, you can notice it in a clean ummorpg or even some published games made with the asset.

**Comment by jonmalave** [comment]
> Hey guys. So this only happens in a build, not if you run host mode in Editor?

Yes, Correct.

**Comment by jon-malave** [comment]
Wow! Seriously... it's been a whole month @vis2k and this is still not resolved? Something that should be working out the box and an issue that seems to have gone unresolved for years apparently. So frigging sad man!!! Just close this ticket or ignore it completely (as clearing you are) as i'm totally done with your crap level of support! I have given this asset a chance year after year and still your lack of support for this asset is unbelievable.  

On another note... i'd highly recommend anyone seeing this to move over to MMORPG Kit, @insthync is far better at providing support for his asset than vis2k. Features wise I think MMORPG Kit totally kicks uMMORPGs ass and way cheaper!!!

https://assetstore.unity.com/packages/templates/systems/mmorpg-kit-2d-3d-survival-110188

**Comment by jonmalave** [comment]
@vis2k there you go i closed it for you so you can cross one more thing off your list to worry about... since you don't really want to fix it anyway. Call this a friendly gesture of helping you do less work so you can focus on your new dotnet asset and continue shitting on your support for assets people paid alot of money for....
