### ISSUE TITLE
Build error fresh install 2019.3.10f1

### ISSUE THREAD

**Issue by skymeson** [vis2k/uMMORPG#38]
**Versions (please complete the following information)**
 - Unity Version: [e.g. 2019.3.10f1]
 - uMMORPG Version: [e.g. V1.189]
 - Are you using a fresh uMMORPG version without any modifications? [e.g. yes/no]
yes

**Describe the bug**
With new project, I import Mirror from asset store. I then import uMMORPG from asset store. There are some errors associated with PackageManagerUI which I get rid of by removing that package. Then another error remains related to uMMORPG. 

""Assets\uMMORPG\Scripts\NetworkManagerMMO.cs(459,130): error CS0117: 'AddPlayerMessage' does not contain a definition for 'value'""

That line disables obsolete warning. My guess is it is now removed from latest version but this line hasn't been updated yet. 

#pragma warning disable CS0618 // AddPlayerMessage.value is obsolete
                Utils.InvokeMany(typeof(NetworkManagerMMO), this, "OnServerAddPlayer_", account, go, conn, new AddPlayerMessage{ value=BitConverter.GetBytes(message.index) }); // old hook
#pragma warning restore CS0618 // AddPlayerMessage.value is obsolete

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor '2019.3.10f1'
2. Build for Windows 'PC'
3. Import Mirror
4. import uMMORGP
5. See error
""Assets\uMMORPG\Scripts\NetworkManagerMMO.cs(459,130): error CS0117: 'AddPlayerMessage' does not contain a definition for 'value'""

**Expected behavior**
It should compile. 

**Screenshots/Video**
If applicable, add screenshots/videos to help explain your problem.

**System (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by Undermozes** [comment]
You can remove this line, its not used anymore 

> #pragma warning disable CS0618 // AddPlayerMessage.value is obsolete
> Utils.InvokeMany(typeof(NetworkManagerMMO), this, "OnServerAddPlayer_", account, go, conn, new AddPlayerMessage{ value=BitConverter.GetBytes(message.index) }); // old hook
> #pragma warning restore CS0618 // AddPlayerMessage.value is obsolete

**Comment by miwarnec** [comment]
Don't update Mirror yourself. wait until I do it, then you don't have to worry about it :)
