### ISSUE TITLE
Trying to send command for object without authority. Pet.CmdSetAutoAttack

### ISSUE THREAD

**Issue by Undermozes** [vis2k/uMMORPG#39]
**Versions (please complete the following information)**
 - Unity Version: [e.g. 2019.2.14f1]
 - uMMORPG Version: [e.g. V1.189]
 - Are you using a fresh uMMORPG version without any modifications? [yes]

**Describe the bug**
When you push the button defend or attack on your pet (To change the bool) the editor throws the message 
Trying to send command for object without authority. Pet.CmdSetAutoAttack
And when u do it with defend
Trying to send command for object without authority. Pet.CmdSetDefendOwner

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor
2. Get Ummorpg from the store 
3. Buy a pet
4. Click on attack or defend
5. See error

**System (please complete the following information):**
 - Operating System [e.g. Windows 10]

**Comment by miwarnec** [comment]
checking

**Comment by miwarnec** [comment]
fixed in V1.190 - pending review
thanks!
