### ISSUE TITLE
Character model from character selection screen is visible ingame at the right bottom of the map

### ISSUE THREAD

**Issue by fixxiefixx** [vis2k/uMMORPG#4]
**Versions (please complete the following information)**
 - Unity Version: 2017.4.14f1
 - uMMORPG Version: 1.146
 - Are you using a fresh uMMORPG version without any modifications? yes

**Describe the bug**
On the client a the character selecten model is still visible ingame after character confirmation.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor 2017.4.14f1
2. Import uMMORPG Version 1.146
3. Build for Windows x86
3. Run the build and start server
4. Run a second instance of the build and connect to the server
5. create a character of class Warrior, select it and click the "Start" button.
6. Go to the right bottom of the map.
7. You will see the character from the character selection screen.

**Expected behavior**
I expect that the characters from the character selection screen disappers after the character spawns at the "ingame world".

**Screenshots/Video**
https://www.dropbox.com/s/rozuhjatynweqyz/ummorpg_character_selection_bug.JPG?dl=0

**System (please complete the following information):**
 - Operating System Windows 10  (x64) Home

**Additional context**

**Comment by miwarnec** [comment]
thanks for the report, I can reproduce it. looking into a fix now

**Comment by miwarnec** [comment]
fixed, will be in next version. thanks
