### ISSUE TITLE
Login with a typo results in new account registered

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#40]
**Versions (please complete the following information)**
- happens in all vis2k assets

**Describe the bug**
Just create an account (e.g. "admin") and after that try logging in with a typo in the account name (e.g. "admire") - the result is the generation of yet another account.

This is not just un-manageable for the administrator of such a game, it also results in a lot of confusion on the users end.

**Comment by miwarnec** [comment]
you are supposed to implement your own account system.

**Comment by jonmalave** [comment]
> you are supposed to implement your own account system.

most of your user base are noobs who don't code... and just want to drag and drop a game together! you know exactly what you are doing when you claim an asset to be the "easiest MMORPG engine to use on the planet" promoting it as super user friendly to make your sales but yet can't properly provide fundamental features required to manage a game for your noob user base!! 

you abuse your community and customers but bating them, making a sale then shrug them off "with a too bad go figure it out attitude" 

you are really sad person... and your business practices will come back to haunt you... keep up the great work!
