### ISSUE TITLE
Cannot change password

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#42]
**Versions (please complete the following information)**
- happens in all vis2k assets

**Describe the bug**
It is not possible for the end user to change the password on a existing account.

This is a major dilemma as the passwords are saved encrypted in the database (which is a good thing) - as this makes it impossible for the administrator to change the manually password for the user (Which is also just a emergency solution).

Impossible to get this sorted out in a proper way on a live project!

**Comment by miwarnec** [comment]
use sql

**Comment by jonmalave** [comment]
> use sql

@vis2k but yet "uMMORPG is the most simple and easiest to use MMO engine on the planet" great way to get sales and lore in all the noobs to buy your asset that is missing fundamental admin features to help them manage their game.
