### ISSUE TITLE
Network Zone AddOn is out of date

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#44]
Any ummorpg version

The asset author usually recommends the "Network Zone Addon" when people ask about multi scene functionality for ummorpg.

But that very addon is out of date and does not work with all the recent ummorpg and Mirror (Network) changes we had.

**Comment by jonmalave** [comment]
> Any ummorpg version
> 
> The asset author usually recommends the "Network Zone Addon" when people ask about multi scene functionality for ummorpg.
> 
> But that very addon is out of date and does not work with all the recent ummorpg and Mirror (Network) changes we had.

what a joke!! wow...
