### ISSUE TITLE
Monster/Player position desync

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#45]
**Versions (please complete the following information)**
uMMORPG Classic

**To Reproduce**
Use a server and two or more clients and move around, also watch monsters move around. After a while the server position and the client positions are slightly out of sync. This seems to happen far more often for monsters than for players (the player issue might have been fixed by now).

Fix: A RPC call when a entity ends its movement solves the issue.

**Comment by miwarnec** [comment]
@wovencode why are you here?

**Comment by wovencode** [comment]
Your answer is rude.

Im reporting bugs and issues.

Guess im the only one who is still reporting things that should get fixed. If you don't want to bother with bug reports it might be the best to remove the issue tracker.

**Comment by vis2k** [comment]
Please move on and leave me alone

**Comment by jonmalave** [comment]
> @wovencode why are you here?

Wow!!! @vis2k what is your problem, he even offered a fix and you still need to be a dick about it? 

Why not ask.... why are you still selling an asset that has fundamental things broken with it out the box!! Fix your damn asset and stop scamming people into buying your next asset that your trying to cash in on while neglecting your flagship product. 

If you don't want to deal with support requests, then don't sell assets very simple solution! So deal with it...
