### ISSUE TITLE
Pet

### ISSUE THREAD

**Issue by reyser-eth** [vis2k/uMMORPG#6]
**Versions (please complete the following information)**
 - Unity Version: 2017.4.9f1
 - uMMORPG Version: V1.150
 - Are you using a fresh uMMORPG version without any modifications? Yes

**Describe the bug**
Pet can't be summoned after Pet Level & Exp = Player Level & Exp

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Run The Game on Unity
2. Leveling the character + Pet Character to level 4 Exp 36/40
3. Unsummon and Summon it (Make sure we still able to summon pet)
4. Kill 1 Monster to Max Level  Exp 40/40
5. Unsummon pet and Summon it again the error will came out

**Screenshots/Video**
https://cdn.discordapp.com/attachments/286593538257584140/523165615305916436/Pet.mp4

**System (please complete the following information):**
 - Operating System  Windows 7 Pro

**Comment by miwarnec** [comment]
Thanks, fixed this already in one of the last versions
