### ISSUE TITLE
Server restart -> dead player

### ISSUE THREAD

**Issue by DevSocks** [vis2k/uMMORPG#7]
**Versions (please complete the following information)**
 - Unity Version: 2017.4.7f1 LTS
 - uMMORPG Version: 1.151
Fresh install.

**Describe the bug**
UI element on login after server crash

Launch server instance. Launch client -> create character -> kill character - don't respawn -> quit server -> click Got it [client] -> launch server -> click respawn

![capture](https://user-images.githubusercontent.com/45916308/50053879-f6e44800-0109-11e9-9ff5-6ba0fd21537d.PNG)

**Comment by miwarnec** [comment]
thanks, looking into various ways to fix this. should apply to other windows like inventory too..

**Comment by miwarnec** [comment]
Fix will be in V1.152. Thanks for reporting.

**Comment by DevSocks** [comment]
Also happens in 1.35 2D
