### ISSUE TITLE
Out of box ummorpg 1.152 runs with Mirror Errors on linux

### ISSUE THREAD

**Issue by graves2729** [vis2k/uMMORPG#8]
**Versions (please complete the following information)**
 - Unity Version:2017.4.4
 - uMMORPG Version:v1.152
 - Are you using a fresh uMMORPG version without any modifications? [e.g. yes/no]
    If not, then please try to reproduce it in a fresh Version and come back here.
yes fresh version
**Describe the bug**
install ummorpg in clean project click play
**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
open ummorpg 1.152 in a clean project in linux.,

**Expected behavior**
I expected to be able to log in and run the game(no sarcasm)
**Screenshots/Video**
If applicable, add screenshots/videos to help explain your problem.
https://drive.google.com/open?id=1_g-IhAGP_0aKmmkIf_1_NmsgCtTwgvOV
**System (please complete the following information):**
 - Operating System [e.g. Windows 7]
Xubuntu 18.04 64bit
**Additional context**

**Comment by miwarnec** [comment]
Thanks, should be able to reproduce this one. Will let you know when I know more!

**Comment by miwarnec** [comment]
Someone mentioned fixing the problem like this:
![image](https://user-images.githubusercontent.com/16416509/50332971-131a2780-0504-11e9-8a5e-bca9bd4f60f3.png)

Can you try that?

**Comment by graves2729** [comment]
Things i have tried:
Deleting Unity all together. Reinstalling - Same effect
Installing unity on a new Linux computer. - Same Effect
Installed Same version of uSURVIVE - Same Effect

update: tested with Unity version 2017 4.0f1 (closest i can come client wise to version in linux ) - Same effect
update: Tested with Unity version 2018.2.2f1 - No errors

1.51 contained no errors. The change is something very recent.

It could be related to the version but this would be my first problem with 4.4 since the beginning.

**Comment by miwarnec** [comment]
Do you still have V1.151 on your hard drive?
If yes, can you use the mirror dlls of that version and try with the latest? See if it works or not?

**Comment by graves2729** [comment]
I do not have a copy of 151 saved. I ignorantly didn't think i would have a operational issue between 151 and 152.  So when 152 came out i just upgraded. 1.148 is the closest i can come to the problem version of uMMO

**Comment by miwarnec** [comment]
Can you try the mirror dlls from 148 for 152 on linux please?

**Comment by miwarnec** [comment]
Tried to install Unity on Ubuntu 18.04 today, but getting all kinds of errors.
Trying Linux Mint next

**Comment by miwarnec** [comment]
Tried Unity on another computer with Linux Mint. Unity shows me empty error messages.
@graves2729 can you try the mirror dlls mentioned above? I am having trouble reproducing this

**Comment by miwarnec** [comment]
probably works fine with source drop-in now, closing
