### ISSUE TITLE
1155 LLAPITransport is not compatible with Network Manager

### ISSUE THREAD

**Issue by epicality85** [vis2k/uMMORPG#9]
Building WebGL client, added LLAPITransport to Network Manager, removed Telepathy, assigned LLAPITransport to Transport. Recurring error: (Server & Play Unity; Windows Server and Unity Client; Linux Server & WebGL Client)
`host id out of bound id {-1} max id should be greater 0 and less than {0}
UnityEngine.Networking.NetworkTransport:ReceiveFromHost()
Mirror.LLAPITransport:ProcessClientMessage() (at Assets/uMMORPG/Plugins/Mirror/Runtime/Transport/LLAPITransport.cs:118)
Mirror.LLAPITransport:Update() (at Assets/uMMORPG/Plugins/Mirror/Runtime/Transport/LLAPITransport.cs:157)`

**Comment by miwarnec** [comment]
fixed, use latest mirror
